/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.training.display;

import java.util.Random;

/**
 *
 * @author Alessandro
 */
public class InformationPane extends javax.swing.JFrame {
    String[] nomi = {"Arturo", "Antonio", "Alicio", "Bernardo", "Caio", "Dante", 
        "Ernesto", "Enzo", "Falco", "Franco", "Giuseppe", "Gertrudo", "Genoveffo", "Giocondo", 
        "Ilario", "James", "Ken", "Lucrezio", "Leonardo", "Lucio", "Mario", "Minosse",
        "Narciso", "Nerone", "Osvaldo", "Paolino", "Pino", "Pierino", "Peppino", 
        "Qui", "Quo", "Qua", "Ramarro", "Severo", "Salomone", "Traiano", "Timone", 
        "Ugo", "Valentino", "Zagabrio"};
    
    String[] cognomi = {"da Lampedusa", "Bevi l'Acqua"};
    
    String[] descrizioni = {"Ha moglie e figli", "Gli piacciono le anatre", 
        "In cantina possiede una pala", "Domani ha un impegno molto importante", 
        "Ha un tic insopportabile", "Il suo hobby è la pesca", 
        "Quando torna a casa guarda i cantieri"};

        
    /**
     * Creates new form informationPane
     * @param info
     */
    public InformationPane(String info) {
        initComponents();
        String[] informazioni = info.split("-");
        jLabelAttacco.setText(informazioni[1]);
        jLabelDifesa.setText(informazioni[2]);
        Random random = new Random();
        int indiceNome = random.nextInt(nomi.length);
        int indiceCognome = random.nextInt(cognomi.length);
        jLabelNome.setText(nomi[indiceNome] + " " + cognomi[indiceCognome]);
        jLabelVita.setText(informazioni[0]);
        int indiceDescrizione = random.nextInt(descrizioni.length);
        jLabelDescrizione.setText(descrizioni[indiceDescrizione]);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelVita = new javax.swing.JLabel();
        jLabelAttacco = new javax.swing.JLabel();
        jLabelDifesa = new javax.swing.JLabel();
        jLabelDescrizione = new javax.swing.JLabel();

        setTitle("Information Panel");
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Vita");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Attacco");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Difesa");

        jLabelNome.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabelNome.setText("jLabel4");

        jLabelVita.setText("jLabel5");

        jLabelAttacco.setText("jLabel6");

        jLabelDifesa.setText("jLabel7");

        jLabelDescrizione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescrizione.setText("Vita, Morte e miracoli");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescrizione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDifesa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelVita))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAttacco)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelVita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAttacco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDifesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescrizione, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new informationPane().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new InformationPane().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAttacco;
    private javax.swing.JLabel jLabelDescrizione;
    private javax.swing.JLabel jLabelDifesa;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelVita;
    // End of variables declaration//GEN-END:variables
}
